language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Disabled for now since cause more pain than gain
#  - "nightly" # currently points to 3.6-dev
#  - "pypy"
#  - "pypy3"

#  # works properly without installed gevent, so currenly commented to not fail on CI
#  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
#  # maintainers to fix their pypy-dev package.
#  - "pypy"

# command to install dependencies
install: "pip install -r requirements_testing.txt"

env:
  - CODACY_PROJECT_TOKEN=4620615bad6043d3b623eff21a60130a

 # command to run tests
script: nosetests --with-coverage --cover-package=pybenchmark tests/

after_success:
  - coverage xml
  - python-codacy-coverage -v -r coverage.xml
